// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

export const awsmobile =  {
    aws_project_region: "us-east-1",
    aws_cognito_identity_pool_id: "us-east-1:0c4629df-3bcc-49b5-be6e-5861d5283b56",
    aws_cognito_region: "us-east-1",
    aws_user_pools_id: "us-east-1_s9iDqPquj",
    aws_user_pools_web_client_id: "1271f4r7a3f24kk53j6emll9nb",
    aws_user_files_s3_bucket: "client6c4d284790104a1c85ba6a0f621440bb",
    aws_user_files_s3_bucket_region: "us-east-1"
};